@startuml
autonumber
actor "Receptionist" as RCPT

activate RCPT
RCPT -> ":System" : Starts by scheduling the vaccine
activate ":System"
":System" --> RCPT : Request data (snsUserNumber)
deactivate ":System"

RCPT -> ":System" : Types requested data
activate ":System"
":System" --> RCPT : Shows vaccination center list and ask to select one
deactivate ":System"
RCPT -> ":System" : Selects a vaccination center
activate ":System"
":System" --> RCPT : Request data (date and time)
deactivate ":System"
RCPT -> ":System" : Types requested data
activate ":System"
":System" --> RCPT : Shows vaccine type list and ask to select one
deactivate ":System"
RCPT -> ":System" : Selects a vaccine type
activate ":System"
":System" --> RCPT : Shows the data and requests a confirmation
deactivate ":System"

RCPT -> ":System" : Confirms the data
activate ":System"
":System" --> RCPT : Informs operation success
deactivate ":System"

deactivate RCPT

@enduml